const views = require('point-of-view')
const marko = require('marko')
const htmlMinifier = require('html-minifier')
const htmlMinifyStream = require('html-minify-stream')

module.exports = {
  views,
  viewConfig: {
    engine: { marko },
    templates: 'components',
    includeViewExtension: true,
    options: {
      // useHtmlMinifier: htmlMinifier,
      useHtmlMinifyStream: htmlMinifyStream,
      htmlMinifierOptions: {
        collapseWhitespace: true,
        conservativeCollapse: true,
        collapseBooleanAttributes: true,
        removeEmptyAttributes: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        removeOptionalTags: true,
        removeAttributeQuotes: true,
        removeEmptyAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true
      }
    }
  }
}
